#!/bin/bash

MAXLEN=0
if command ps -a | grep -w 'tor' >'/dev/null' 2>&1; then 
	CURSTAT='active'
	if grep 'NODERELOAD=true' 'scuttle.conf' >'/dev/null'; then 
		MODE='node reloader'
	else MODE='static entrynode'
	fi
else
	CURSTAT='inactive'
	MODE='N/A'
fi
STATUSCMD="$(echo -e "TOR: $CURSTAT\n\nMODE: $MODE\n")"
while IFS= read -r LN; do
    (( ${#LN} > MAXLEN )) && MAXLEN=${#LN}
done <<< "$STATUSCMD"
echo ' ╔='$(printf "%-${MAXLEN}s" | tr ' ' '=')'=╗'
while IFS= read -r LN; do
    echo " ║ $LN $(printf "%-$(($MAXLEN-${#LN}))s" | tr ' ' ' ')║"
done <<< "$STATUSCMD"
echo ' ╚='$(printf "%-${MAXLEN}s" | tr ' ' '=')'=╝'

unset MAXLEN STATUSCMD CURSTAT
